---
- name: Set authorized Key from jumphost
  authorized_key:
    user: student
    state: present
    key: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"

- name: Enable Passwordless sudo for wheel group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'