---
- name: Set authorized Key from jumphost
  authorized_key:
    user: student
    state: present
    key: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"

- name: Enable Passwordless sudo for wheel group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Configure Auto Login
  ini_file:
    path: /etc/gdm/custom.conf
    section: daemon
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - option: AutomaticLoginEnable
      value: "True"
    - option: AutomaticLogin
      value: student
